### ISSUE TITLE
 Suggestion to use OPT as default mode in "FlexSC/Config.conf"

### ISSUE THREAD

**Issue by weikengchen** [wangxiao1254/FlexSC#1]
I guess it is only for me... I tried to debug why output is not available, and finally, finally, found that result for runXXX.sh test example is not out if use CIRCUIT mode - there will be Null Pointer Exception.

So I guess to use OPT as the default mode in "FlexSC/Config.conf".

Or is there anything wrong with my environtment?

@kartik1507

**Comment by wangxiao1254** [comment]
Done. If you are using it for 2PC, you are welcome to our C++ version at github.com/emp-toolkit (much much more efficient and support malicious security if you need).

**Comment by weikengchen** [comment]
Yes. I came from SCORAM and found this implementation with Recursive Circuit ORAM. 

It seems emp-toolkit has no built-in ORAM. (However, as the parameter of ORAM is very customized and how to construct the circuit of Circuit ORAM is already available here, asking for this is not reasonable...)
